name: Terraform CI for VPC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  - AWS_REGION: "us-east-1"
  - ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION = true

jobs:
  Deploy_Terraform:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Replace with your actual IAM Role ARN
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0" # Specify your Terraform version

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        # Only run apply if we are on the main branch and it's a push/merge event
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
